package net.sf.iquiver.om;


import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.Transaction;

  
    
  
/**
 * This class was autogenerated by Torque on:
 *
 * [Sun Apr 04 20:29:12 CEST 2004]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to UserGroupClientLnk
 */
public abstract class BaseUserGroupClientLnk extends BaseObject
{
    /** The Peer class */
    private static final UserGroupClientLnkPeer peer =
        new UserGroupClientLnkPeer();

        
    /** The value for the clientId field */
    private int clientId;
      
    /** The value for the userGroupId field */
    private long userGroupId;
  
    
    /**
     * Get the ClientId
     *
     * @return int
     */
    public int getClientId()
    {
        return clientId;
    }

                              
    /**
     * Set the value of ClientId
     *
     * @param v new value
     */
    public void setClientId(int v) throws TorqueException
    {
    
                  if (this.clientId != v)
              {
            this.clientId = v;
            setModified(true);
        }
    
                          
                if (aClient != null && !(aClient.getClientId() == v))
                {
            aClient = null;
        }
      
              }
  
    /**
     * Get the UserGroupId
     *
     * @return long
     */
    public long getUserGroupId()
    {
        return userGroupId;
    }

                              
    /**
     * Set the value of UserGroupId
     *
     * @param v new value
     */
    public void setUserGroupId(long v) throws TorqueException
    {
    
                  if (this.userGroupId != v)
              {
            this.userGroupId = v;
            setModified(true);
        }
    
                          
                if (aUserGroup != null && !(aUserGroup.getUserGroupId() == v))
                {
            aUserGroup = null;
        }
      
              }
  
      
    
                  
    
        private Client aClient;

    /**
     * Declares an association between this object and a Client object
     *
     * @param v Client
     * @throws TorqueException
     */
    public void setClient(Client v) throws TorqueException
    {
            if (v == null)
        {
                    setClientId(0);
                  }
        else
        {
            setClientId(v.getClientId());
        }
                aClient = v;
    }

                                            
    /**
     * Get the associated Client object
     *
     * @return the associated Client object
     * @throws TorqueException
     */
    public Client getClient() throws TorqueException
    {
        if (aClient == null && (this.clientId > 0))
        {
                          aClient = ClientPeer.retrieveByPK(SimpleKey.keyFor(this.clientId));
              
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Client obj = ClientPeer.retrieveByPK(this.clientId);
               obj.addUserGroupClientLnks(this);
            */
        }
        return aClient;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
           */
    public void setClientKey(ObjectKey key) throws TorqueException
    {
      
                        setClientId(((NumberKey) key).intValue());
                  }
    
    
                  
    
        private UserGroup aUserGroup;

    /**
     * Declares an association between this object and a UserGroup object
     *
     * @param v UserGroup
     * @throws TorqueException
     */
    public void setUserGroup(UserGroup v) throws TorqueException
    {
            if (v == null)
        {
                    setUserGroupId(0);
                  }
        else
        {
            setUserGroupId(v.getUserGroupId());
        }
                aUserGroup = v;
    }

                                            
    /**
     * Get the associated UserGroup object
     *
     * @return the associated UserGroup object
     * @throws TorqueException
     */
    public UserGroup getUserGroup() throws TorqueException
    {
        if (aUserGroup == null && (this.userGroupId > 0))
        {
                          aUserGroup = UserGroupPeer.retrieveByPK(SimpleKey.keyFor(this.userGroupId));
              
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               UserGroup obj = UserGroupPeer.retrieveByPK(this.userGroupId);
               obj.addUserGroupClientLnks(this);
            */
        }
        return aUserGroup;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
           */
    public void setUserGroupKey(ObjectKey key) throws TorqueException
    {
      
                        setUserGroupId(((NumberKey) key).longValue());
                  }
       
                
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("ClientId");
              fieldNames.add("UserGroupId");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("ClientId"))
        {
                return new Integer(getClientId());
            }
          if (name.equals("UserGroupId"))
        {
                return new Long(getUserGroupId());
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(UserGroupClientLnkPeer.CLIENT_ID))
        {
                return new Integer(getClientId());
            }
          if (name.equals(UserGroupClientLnkPeer.USER_GROUP_ID))
        {
                return new Long(getUserGroupId());
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getClientId());
            }
              if (pos == 1)
        {
                return new Long(getUserGroupId());
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(UserGroupClientLnkPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    UserGroupClientLnkPeer.doInsert((UserGroupClientLnk) this, con);
                    setNew(false);
                }
                else
                {
                    UserGroupClientLnkPeer.doUpdate((UserGroupClientLnk) this, con);
                }
            }

                      alreadyInSave = false;
        }
      }


                                                
  
    private final SimpleKey[] pks = new SimpleKey[2];
    private final ComboKey comboPK = new ComboKey(pks);
    
    /**
     * Set the PrimaryKey with an ObjectKey
     *
     * @param key
     */
    public void setPrimaryKey(ObjectKey key) throws TorqueException
    {
        SimpleKey[] keys = (SimpleKey[]) key.getValue();
        SimpleKey tmpKey = null;
                      setClientId(((NumberKey)keys[0]).intValue());
                        setUserGroupId(((NumberKey)keys[1]).longValue());
              }

    /**
     * Set the PrimaryKey using SimpleKeys.
     *
         * @param int clientId
         * @param long userGroupId
         */
    public void setPrimaryKey( int clientId, long userGroupId)
        throws TorqueException
    {
            setClientId(clientId);
            setUserGroupId(userGroupId);
        }

    /**
     * Set the PrimaryKey using a String.
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setPrimaryKey(new ComboKey(key));
    }
  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
              pks[0] = SimpleKey.keyFor(getClientId());
                  pks[1] = SimpleKey.keyFor(getUserGroupId());
                  return comboPK;
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public UserGroupClientLnk copy() throws TorqueException
    {
        return copyInto(new UserGroupClientLnk());
    }
  
    protected UserGroupClientLnk copyInto(UserGroupClientLnk copyObj) throws TorqueException
    {
          copyObj.setClientId(clientId);
          copyObj.setUserGroupId(userGroupId);
  
                    copyObj.setClientId(0);
                              copyObj.setUserGroupId(0);
            
        
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public UserGroupClientLnkPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("UserGroupClientLnk:\n");
        str.append("ClientId = ")
           .append(getClientId())
           .append("\n");
        str.append("UserGroupId = ")
           .append(getUserGroupId())
           .append("\n");
        return(str.toString());
    }
}
