package net.sf.iquiver.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Mar 11 21:51:09 CET 2004]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to ContentParser
 */
public abstract class BaseContentParser extends BaseObject
{
    /** The Peer class */
    private static final ContentParserPeer peer =
        new ContentParserPeer();

        
    /** The value for the contentParserId field */
    private int contentParserId;
      
    /** The value for the contentParserImplementation field */
    private String contentParserImplementation;
      
    /** The value for the contentParserName field */
    private String contentParserName;
  
    
    /**
     * Get the ContentParserId
     *
     * @return int
     */
    public int getContentParserId()
    {
        return contentParserId;
    }

                                              
    /**
     * Set the value of ContentParserId
     *
     * @param v new value
     */
    public void setContentParserId(int v) throws TorqueException
    {
    
                  if (this.contentParserId != v)
              {
            this.contentParserId = v;
            setModified(true);
        }
    
          
                                  
        // update associated ContentType
        if (collContentTypes != null)
        {
            for (int i = 0; i < collContentTypes.size(); i++)
            {
                ((ContentType) collContentTypes.get(i))
                    .setContentParserId(v);
            }
        }
                      }
  
    /**
     * Get the ContentParserImplementation
     *
     * @return String
     */
    public String getContentParserImplementation()
    {
        return contentParserImplementation;
    }

                        
    /**
     * Set the value of ContentParserImplementation
     *
     * @param v new value
     */
    public void setContentParserImplementation(String v) 
    {
    
                  if (!ObjectUtils.equals(this.contentParserImplementation, v))
              {
            this.contentParserImplementation = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the ContentParserName
     *
     * @return String
     */
    public String getContentParserName()
    {
        return contentParserName;
    }

                        
    /**
     * Set the value of ContentParserName
     *
     * @param v new value
     */
    public void setContentParserName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.contentParserName, v))
              {
            this.contentParserName = v;
            setModified(true);
        }
    
          
              }
  
         
                                
            
    /**
     * Collection to store aggregation of collContentTypes
     */
    protected List collContentTypes;

    /**
     * Temporary storage of collContentTypes to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initContentTypes()
    {
        if (collContentTypes == null)
        {
            collContentTypes = new ArrayList();
        }
    }

    /**
     * Method called to associate a ContentType object to this object
     * through the ContentType foreign key attribute
     *
     * @param l ContentType
     * @throws TorqueException
     */
    public void addContentType(ContentType l) throws TorqueException
    {
        getContentTypes().add(l);
        l.setContentParser((ContentParser) this);
    }

    /**
     * The criteria used to select the current contents of collContentTypes
     */
    private Criteria lastContentTypesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getContentTypes(new Criteria())
     *
     * @throws TorqueException
     */
    public List getContentTypes() throws TorqueException
    {
        if (collContentTypes == null)
        {
            collContentTypes = getContentTypes(new Criteria(10));
        }
        return collContentTypes;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContentParser has previously
     * been saved, it will retrieve related ContentTypes from storage.
     * If this ContentParser is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getContentTypes(Criteria criteria) throws TorqueException
    {
        if (collContentTypes == null)
        {
            if (isNew())
            {
               collContentTypes = new ArrayList();
            }
            else
            {
                      criteria.add(ContentTypePeer.CONTENT_PARSER_ID, getContentParserId() );
                      collContentTypes = ContentTypePeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                      criteria.add(ContentTypePeer.CONTENT_PARSER_ID, getContentParserId());
                      if (!lastContentTypesCriteria.equals(criteria))
                {
                    collContentTypes = ContentTypePeer.doSelect(criteria);
                }
            }
        }
        lastContentTypesCriteria = criteria;

        return collContentTypes;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getContentTypes(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getContentTypes(Connection con) throws TorqueException
    {
        if (collContentTypes == null)
        {
            collContentTypes = getContentTypes(new Criteria(10), con);
        }
        return collContentTypes;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContentParser has previously
     * been saved, it will retrieve related ContentTypes from storage.
     * If this ContentParser is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getContentTypes(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collContentTypes == null)
        {
            if (isNew())
            {
               collContentTypes = new ArrayList();
            }
            else
            {
                       criteria.add(ContentTypePeer.CONTENT_PARSER_ID, getContentParserId());
                       collContentTypes = ContentTypePeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                       criteria.add(ContentTypePeer.CONTENT_PARSER_ID, getContentParserId());
                       if (!lastContentTypesCriteria.equals(criteria))
                 {
                     collContentTypes = ContentTypePeer.doSelect(criteria, con);
                 }
             }
         }
         lastContentTypesCriteria = criteria;

         return collContentTypes;
     }

                  
              
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this ContentParser is new, it will return
     * an empty collection; or if this ContentParser has previously
     * been saved, it will retrieve related ContentTypes from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContentParser.
     */
    protected List getContentTypesJoinContentParser(Criteria criteria)
        throws TorqueException
    {
        if (collContentTypes == null)
        {
            if (isNew())
            {
               collContentTypes = new ArrayList();
            }
            else
            {
                            criteria.add(ContentTypePeer.CONTENT_PARSER_ID, getContentParserId());
                            collContentTypes = ContentTypePeer.doSelectJoinContentParser(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(ContentTypePeer.CONTENT_PARSER_ID, getContentParserId());
                        if (!lastContentTypesCriteria.equals(criteria))
            {
                collContentTypes = ContentTypePeer.doSelectJoinContentParser(criteria);
            }
        }
        lastContentTypesCriteria = criteria;

        return collContentTypes;
    }
                            


          
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("ContentParserId");
              fieldNames.add("ContentParserImplementation");
              fieldNames.add("ContentParserName");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("ContentParserId"))
        {
                return new Integer(getContentParserId());
            }
          if (name.equals("ContentParserImplementation"))
        {
                return getContentParserImplementation();
            }
          if (name.equals("ContentParserName"))
        {
                return getContentParserName();
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(ContentParserPeer.CONTENT_PARSER_ID))
        {
                return new Integer(getContentParserId());
            }
          if (name.equals(ContentParserPeer.CONTENT_PARSER_IMPLEMENTATION))
        {
                return getContentParserImplementation();
            }
          if (name.equals(ContentParserPeer.CONTENT_PARSER_NAME))
        {
                return getContentParserName();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getContentParserId());
            }
              if (pos == 1)
        {
                return getContentParserImplementation();
            }
              if (pos == 2)
        {
                return getContentParserName();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(ContentParserPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    ContentParserPeer.doInsert((ContentParser) this, con);
                    setNew(false);
                }
                else
                {
                    ContentParserPeer.doUpdate((ContentParser) this, con);
                }
            }

                                      
                
            if (collContentTypes != null)
            {
                for (int i = 0; i < collContentTypes.size(); i++)
                {
                    ((ContentType) collContentTypes.get(i)).save(con);
                }
            }
                          alreadyInSave = false;
        }
      }


                          
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  contentParserId ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setContentParserId(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setContentParserId(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getContentParserId());
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public ContentParser copy() throws TorqueException
    {
        return copyInto(new ContentParser());
    }
  
    protected ContentParser copyInto(ContentParser copyObj) throws TorqueException
    {
          copyObj.setContentParserId(contentParserId);
          copyObj.setContentParserImplementation(contentParserImplementation);
          copyObj.setContentParserName(contentParserName);
  
                    copyObj.setContentParserId(0);
                        
                                      
                
        List v = getContentTypes();
        for (int i = 0; i < v.size(); i++)
        {
            ContentType obj = (ContentType) v.get(i);
            copyObj.addContentType(obj.copy());
        }
                    
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ContentParserPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("ContentParser:\n");
        str.append("ContentParserId = ")
           .append(getContentParserId())
           .append("\n");
        str.append("ContentParserImplementation = ")
           .append(getContentParserImplementation())
           .append("\n");
        str.append("ContentParserName = ")
           .append(getContentParserName())
           .append("\n");
        return(str.toString());
    }
}
