package net.sf.iquiver.om;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

import org.apache.torque.NoRowsException;
import org.apache.torque.TooManyRowsException;
import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.BasePeer;
import org.apache.torque.util.Criteria;

import com.workingdogs.village.DataSetException;
import com.workingdogs.village.QueryDataSet;
import com.workingdogs.village.Record;

// Local classes
import net.sf.iquiver.om.map.*;


  
  
  
/**
 * This class was autogenerated by Torque on:
 *
 * [Sat Mar 20 16:37:12 CET 2004]
 *
 */
public abstract class BaseContentSourcePeer
    extends net.sf.iquiver.util.om.CacheBackedPeer
{

    /** the default database name for this class */
    public static final String DATABASE_NAME = "iquiver";

     /** the table name for this class */
    public static final String TABLE_NAME = "iq_content_source";

    /**
     * @return the map builder for this peer
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static MapBuilder getMapBuilder()
        throws TorqueException
    {
        return getMapBuilder(ContentSourceMapBuilder.CLASS_NAME);
    }

      /** the column name for the CONTENT_SOURCE_ID field */
    public static final String CONTENT_SOURCE_ID;
      /** the column name for the CONTENT_SOURCE_TYPE_ID field */
    public static final String CONTENT_SOURCE_TYPE_ID;
      /** the column name for the TRANSPORT_ID field */
    public static final String TRANSPORT_ID;
      /** the column name for the PUBLISHER_ID field */
    public static final String PUBLISHER_ID;
      /** the column name for the CONTENT_SOURCE_NAME field */
    public static final String CONTENT_SOURCE_NAME;
      /** the column name for the CONTENT_SOURCE_DESC field */
    public static final String CONTENT_SOURCE_DESC;
      /** the column name for the CONTENT_SOURCE_UPDATE_TIMESPAN field */
    public static final String CONTENT_SOURCE_UPDATE_TIMESPAN;
      /** the column name for the IS_AUTHENTIFICATION_REQUIRED field */
    public static final String IS_AUTHENTIFICATION_REQUIRED;
  
    static
    {
          CONTENT_SOURCE_ID = "iq_content_source.CONTENT_SOURCE_ID";
          CONTENT_SOURCE_TYPE_ID = "iq_content_source.CONTENT_SOURCE_TYPE_ID";
          TRANSPORT_ID = "iq_content_source.TRANSPORT_ID";
          PUBLISHER_ID = "iq_content_source.PUBLISHER_ID";
          CONTENT_SOURCE_NAME = "iq_content_source.CONTENT_SOURCE_NAME";
          CONTENT_SOURCE_DESC = "iq_content_source.CONTENT_SOURCE_DESC";
          CONTENT_SOURCE_UPDATE_TIMESPAN = "iq_content_source.CONTENT_SOURCE_UPDATE_TIMESPAN";
          IS_AUTHENTIFICATION_REQUIRED = "iq_content_source.IS_AUTHENTIFICATION_REQUIRED";
          if (Torque.isInit())
        {
            try
            {
                getMapBuilder(ContentSourceMapBuilder.CLASS_NAME);
            }
            catch (Exception e)
            {
                log.error("Could not initialize Peer", e);
            }
        }
        else
        {
            Torque.registerMapBuilder(ContentSourceMapBuilder.CLASS_NAME);
        }
    }
 
    /** number of columns for this peer */
    public static final int numColumns =  8;

    /** A class that can be returned by this peer. */
    protected static final String CLASSNAME_DEFAULT =
        "net.sf.iquiver.om.ContentSource";

    /** A class that can be returned by this peer. */
    protected static final Class CLASS_DEFAULT = initClass(CLASSNAME_DEFAULT);

    /**
     * Class object initialization method.
     *
     * @param className name of the class to initialize
     * @return the initialized class
     */
    private static Class initClass(String className)
    {
        Class c = null;
        try
        {
            c = Class.forName(className);
        }
        catch (Throwable t)
        {
            log.error("A FATAL ERROR has occurred which should not "
                + "have happened under any circumstance.  Please notify "
                + "the Torque developers <torque-dev@db.apache.org> "
                + "and give as many details as possible (including the error "
                + "stack trace).", t);

            // Error objects should always be propogated.
            if (t instanceof Error)
            {
                throw (Error) t.fillInStackTrace();
            }
        }
        return c;
    }

    /**
     * Get the list of objects for a ResultSet.  Please not that your
     * resultset MUST return columns in the right order.  You can use
     * getFieldNames() in BaseObject to get the correct sequence.
     *
     * @param results the ResultSet
     * @return the list of objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List resultSet2Objects(java.sql.ResultSet results)
            throws TorqueException
    {
        try
        {
            QueryDataSet qds = null;
            List rows = null;
            try
            {
                qds = new QueryDataSet(results);
                rows = getSelectResults(qds);
            }
            finally
            {
                if (qds != null)
                {
                    qds.close();
                }
            }

            return populateObjects(rows);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
        catch (DataSetException e)
        {
            throw new TorqueException(e);
        }
    }


  
    /**
     * Method to do inserts.
     *
     * @param criteria object used to create the INSERT statement.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static ObjectKey doInsert(Criteria criteria)
        throws TorqueException
    {
        return BaseContentSourcePeer
            .doInsert(criteria, (Connection) null);
    }

    /**
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object used to create the INSERT statement.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static ObjectKey doInsert(Criteria criteria, Connection con)
        throws TorqueException
    {
                                                        // check for conversion from boolean to Y/N
        if (criteria.containsKey(IS_AUTHENTIFICATION_REQUIRED))
        {
            Object possibleBoolean = criteria.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
      
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        if (con == null)
        {
            return BasePeer.doInsert(criteria);
        }
        else
        {
            return BasePeer.doInsert(criteria, con);
        }
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * @param criteria object containing the columns to add.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void addSelectColumns(Criteria criteria)
            throws TorqueException
    {
          criteria.addSelectColumn(CONTENT_SOURCE_ID);
          criteria.addSelectColumn(CONTENT_SOURCE_TYPE_ID);
          criteria.addSelectColumn(TRANSPORT_ID);
          criteria.addSelectColumn(PUBLISHER_ID);
          criteria.addSelectColumn(CONTENT_SOURCE_NAME);
          criteria.addSelectColumn(CONTENT_SOURCE_DESC);
          criteria.addSelectColumn(CONTENT_SOURCE_UPDATE_TIMESPAN);
          criteria.addSelectColumn(IS_AUTHENTIFICATION_REQUIRED);
      }

    /**
     * Create a new object of type cls from a resultset row starting
     * from a specified offset.  This is done so that you can select
     * other rows than just those needed for this object.  You may
     * for example want to create two objects from the same row.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static ContentSource row2Object(Record row,
                                             int offset,
                                             Class cls)
        throws TorqueException
    {
        try
        {
            ContentSource obj = (ContentSource) cls.newInstance();
            ContentSourcePeer.populateObject(row, offset, obj);
                  obj.setModified(false);
              obj.setNew(false);

            return obj;
        }
        catch (InstantiationException e)
        {
            throw new TorqueException(e);
        }
        catch (IllegalAccessException e)
        {
            throw new TorqueException(e);
        }
    }

    /**
     * Populates an object from a resultset row starting
     * from a specified offset.  This is done so that you can select
     * other rows than just those needed for this object.  You may
     * for example want to create two objects from the same row.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void populateObject(Record row,
                                      int offset,
                                      ContentSource obj)
        throws TorqueException
    {
        try
        {
                obj.setContentSourceId(row.getValue(offset + 0).asLong());
                  obj.setContentSourceTypeId(row.getValue(offset + 1).asInt());
                  obj.setTransportId(row.getValue(offset + 2).asInt());
                  obj.setPublisherId(row.getValue(offset + 3).asInt());
                  obj.setContentSourceName(row.getValue(offset + 4).asString());
                  obj.setContentSourceDesc(row.getValue(offset + 5).asString());
                  obj.setContentSourceUpdateTimespan(row.getValue(offset + 6).asLong());
                  obj.setIsAuthentificationRequired(row.getValue(offset + 7).asBoolean());
              }
        catch (DataSetException e)
        {
            throw new TorqueException(e);
        }
    }

    /**
     * Method to do selects.
     *
     * @param criteria object used to create the SELECT statement.
     * @return List of selected Objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(Criteria criteria) throws TorqueException
    {
        return populateObjects(doSelectVillageRecords(criteria));
    }

    /**
     * Method to do selects within a transaction.
     *
     * @param criteria object used to create the SELECT statement.
     * @param con the connection to use
     * @return List of selected Objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(Criteria criteria, Connection con)
        throws TorqueException
    {
        return populateObjects(doSelectVillageRecords(criteria, con));
    }

    /**
     * Grabs the raw Village records to be formed into objects.
     * This method handles connections internally.  The Record objects
     * returned by this method should be considered readonly.  Do not
     * alter the data and call save(), your results may vary, but are
     * certainly likely to result in hard to track MT bugs.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelectVillageRecords(Criteria criteria)
        throws TorqueException
    {
        return BaseContentSourcePeer
            .doSelectVillageRecords(criteria, (Connection) null);
    }

    /**
     * Grabs the raw Village records to be formed into objects.
     * This method should be used for transactions
     *
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelectVillageRecords(Criteria criteria, Connection con)
        throws TorqueException
    {
        if (criteria.getSelectColumns().size() == 0)
        {
            addSelectColumns(criteria);
        }

                                                        // check for conversion from boolean to Y/N
        if (criteria.containsKey(IS_AUTHENTIFICATION_REQUIRED))
        {
            Object possibleBoolean = criteria.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
      
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        // BasePeer returns a List of Value (Village) arrays.  The array
        // order follows the order columns were placed in the Select clause.
        if (con == null)
        {
            return BasePeer.doSelect(criteria);
        }
        else
        {
            return BasePeer.doSelect(criteria, con);
        }
    }

    /**
     * The returned List will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List populateObjects(List records)
        throws TorqueException
    {
        List results = new ArrayList(records.size());

        // populate the object(s)
        for (int i = 0; i < records.size(); i++)
        {
            Record row = (Record) records.get(i);
              results.add(ContentSourcePeer.row2Object(row, 1,
                ContentSourcePeer.getOMClass()));
          }
        return results;
    }
 

    /**
     * The class that the Peer will make instances of.
     * If the BO is abstract then you must implement this method
     * in the BO.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static Class getOMClass()
        throws TorqueException
    {
        return CLASS_DEFAULT;
    }

    /**
     * Method to do updates.
     *
     * @param criteria object containing data that is used to create the UPDATE
     *        statement.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(Criteria criteria) throws TorqueException
    {
         BaseContentSourcePeer
            .doUpdate(criteria, (Connection) null);
    }

    /**
     * Method to do updates.  This method is to be used during a transaction,
     * otherwise use the doUpdate(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object containing data that is used to create the UPDATE
     *        statement.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(Criteria criteria, Connection con)
        throws TorqueException
    {
        Criteria selectCriteria = new Criteria(DATABASE_NAME, 2);
                   selectCriteria.put(CONTENT_SOURCE_ID, criteria.remove(CONTENT_SOURCE_ID));
                                                                              // check for conversion from boolean to int
        if (criteria.containsKey(IS_AUTHENTIFICATION_REQUIRED))
        {
            Object possibleBoolean = criteria.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
          
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        if (con == null)
        {
            BasePeer.doUpdate(selectCriteria, criteria);
        }
        else
        {
            BasePeer.doUpdate(selectCriteria, criteria, con);
        }
    }

    /**
     * Method to do deletes.
     *
     * @param criteria object containing data that is used DELETE from database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
     public static void doDelete(Criteria criteria) throws TorqueException
     {
         BaseContentSourcePeer
            .doDelete(criteria, (Connection) null);
     }

    /**
     * Method to do deletes.  This method is to be used during a transaction,
     * otherwise use the doDelete(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object containing data that is used DELETE from database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
     public static void doDelete(Criteria criteria, Connection con)
        throws TorqueException
     {
                                                        // check for conversion from boolean to Y/N
        if (criteria.containsKey(IS_AUTHENTIFICATION_REQUIRED))
        {
            Object possibleBoolean = criteria.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    criteria.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
      
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        if (con == null)
        {
            BasePeer.doDelete(criteria);
        }
        else
        {
            BasePeer.doDelete(criteria, con);
        }
     }

    /**
     * Method to do selects
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(ContentSource obj) throws TorqueException
    {
        return doSelect(buildCriteria(obj));
    }

    /**
     * Method to do inserts
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doInsert(ContentSource obj) throws TorqueException
    {
          obj.setPrimaryKey(doInsert(buildCriteria(obj)));
          obj.setNew(false);
        obj.setModified(false);
    }

    /**
     * @param obj the data object to update in the database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(ContentSource obj) throws TorqueException
    {
        doUpdate(buildCriteria(obj));
        obj.setModified(false);
    }

    /**
     * @param obj the data object to delete in the database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ContentSource obj) throws TorqueException
    {
        doDelete(buildCriteria(obj));
    }

    /**
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(ContentSource) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to insert into the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doInsert(ContentSource obj, Connection con)
        throws TorqueException
    {
          obj.setPrimaryKey(doInsert(buildCriteria(obj), con));
          obj.setNew(false);
        obj.setModified(false);
    }

    /**
     * Method to do update.  This method is to be used during a transaction,
     * otherwise use the doUpdate(ContentSource) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to update in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(ContentSource obj, Connection con)
        throws TorqueException
    {
        doUpdate(buildCriteria(obj), con);
        obj.setModified(false);
    }

    /**
     * Method to delete.  This method is to be used during a transaction,
     * otherwise use the doDelete(ContentSource) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to delete in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ContentSource obj, Connection con)
        throws TorqueException
    {
        doDelete(buildCriteria(obj), con);
    }

    /**
     * Method to do deletes.
     *
     * @param pk ObjectKey that is used DELETE from database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ObjectKey pk) throws TorqueException
    {
        BaseContentSourcePeer
           .doDelete(pk, (Connection) null);
    }

    /**
     * Method to delete.  This method is to be used during a transaction,
     * otherwise use the doDelete(ObjectKey) method.  It will take
     * care of the connection details internally.
     *
     * @param pk the primary key for the object to delete in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ObjectKey pk, Connection con)
        throws TorqueException
    {
        doDelete(buildCriteria(pk), con);
    }

    /** Build a Criteria object from an ObjectKey */
    public static Criteria buildCriteria( ObjectKey pk )
    {
        Criteria criteria = new Criteria();
              criteria.add(CONTENT_SOURCE_ID, pk);
          return criteria;
     }

    /** Build a Criteria object from the data object for this peer */
    public static Criteria buildCriteria( ContentSource obj )
    {
        Criteria criteria = new Criteria(DATABASE_NAME);
              if (!obj.isNew())
                criteria.add(CONTENT_SOURCE_ID, obj.getContentSourceId());
                  criteria.add(CONTENT_SOURCE_TYPE_ID, obj.getContentSourceTypeId());
                  criteria.add(TRANSPORT_ID, obj.getTransportId());
                  criteria.add(PUBLISHER_ID, obj.getPublisherId());
                  criteria.add(CONTENT_SOURCE_NAME, obj.getContentSourceName());
                  criteria.add(CONTENT_SOURCE_DESC, obj.getContentSourceDesc());
                  criteria.add(CONTENT_SOURCE_UPDATE_TIMESPAN, obj.getContentSourceUpdateTimespan());
                  criteria.add(IS_AUTHENTIFICATION_REQUIRED, obj.getIsAuthentificationRequired());
          return criteria;
    }
 
    
        /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static ContentSource retrieveByPK(long pk)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        return retrieveByPK(SimpleKey.keyFor(pk));
    }
  
    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static ContentSource retrieveByPK(ObjectKey pk)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        Connection db = null;
        ContentSource retVal = null;
        try
        {
            db = Torque.getConnection(DATABASE_NAME);
            retVal = retrieveByPK(pk, db);
        }
        finally
        {
            Torque.closeConnection(db);
        }
        return(retVal);
    }

    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static ContentSource retrieveByPK(ObjectKey pk, Connection con)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        Criteria criteria = buildCriteria(pk);
        List v = doSelect(criteria, con);
        if (v.size() == 0)
        {
            throw new NoRowsException("Failed to select a row.");
        }
        else if (v.size() > 1)
        {
            throw new TooManyRowsException("Failed to select only one row.");
        }
        else
        {
            return (ContentSource)v.get(0);
        }
    }

    /**
     * Retrieve a multiple objects by pk
     *
     * @param pks List of primary keys
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List retrieveByPKs(List pks)
        throws TorqueException
    {
        Connection db = null;
        List retVal = null;
        try
        {
           db = Torque.getConnection(DATABASE_NAME);
           retVal = retrieveByPKs(pks, db);
        }
        finally
        {
            Torque.closeConnection(db);
        }
        return(retVal);
    }

    /**
     * Retrieve a multiple objects by pk
     *
     * @param pks List of primary keys
     * @param dbcon the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List retrieveByPKs( List pks, Connection dbcon )
        throws TorqueException
    {
        List objs = null;
        if (pks == null || pks.size() == 0)
        {
            objs = new LinkedList();
        }
        else
        {
            Criteria criteria = new Criteria();
              criteria.addIn( CONTENT_SOURCE_ID, pks );
          objs = doSelect(criteria, dbcon);
        }
        return objs;
    }

 



              
                                              
                
                

    /**
     * selects a collection of ContentSource objects pre-filled with their
     * ContentSourceType objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContentSourcePeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinContentSourceType(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        ContentSourcePeer.addSelectColumns(c);
        int offset = numColumns + 1;
        ContentSourceTypePeer.addSelectColumns(c);


                        c.addJoin(ContentSourcePeer.CONTENT_SOURCE_TYPE_ID,
            ContentSourceTypePeer.CONTENT_SOURCE_TYPE_ID);
        

                                                                                                                                                        // check for conversion from boolean to Y/N
        if ( c.containsKey(IS_AUTHENTIFICATION_REQUIRED) )
        {
            Object possibleBoolean = c.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
                  
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record) rows.get(i);

                            Class omClass = ContentSourcePeer.getOMClass();
                    ContentSource obj1 = (ContentSource) ContentSourcePeer
                .row2Object(row, 1, omClass);
                     omClass = ContentSourceTypePeer.getOMClass();
                    ContentSourceType obj2 = (ContentSourceType)ContentSourceTypePeer
                .row2Object(row, offset, omClass);

            boolean newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                ContentSourceType temp_obj2 = (ContentSourceType)temp_obj1.getContentSourceType();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initContentSources();
                obj2.addContentSource(obj1);
            }
            results.add(obj1);
        }
        return results;
    }
                                                            
                
                

    /**
     * selects a collection of ContentSource objects pre-filled with their
     * Transport objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContentSourcePeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinTransport(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        ContentSourcePeer.addSelectColumns(c);
        int offset = numColumns + 1;
        TransportPeer.addSelectColumns(c);


                        c.addJoin(ContentSourcePeer.TRANSPORT_ID,
            TransportPeer.TRANSPORT_ID);
        

                                                                                                                                                        // check for conversion from boolean to Y/N
        if ( c.containsKey(IS_AUTHENTIFICATION_REQUIRED) )
        {
            Object possibleBoolean = c.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
                  
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record) rows.get(i);

                            Class omClass = ContentSourcePeer.getOMClass();
                    ContentSource obj1 = (ContentSource) ContentSourcePeer
                .row2Object(row, 1, omClass);
                     omClass = TransportPeer.getOMClass();
                    Transport obj2 = (Transport)TransportPeer
                .row2Object(row, offset, omClass);

            boolean newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                Transport temp_obj2 = (Transport)temp_obj1.getTransport();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initContentSources();
                obj2.addContentSource(obj1);
            }
            results.add(obj1);
        }
        return results;
    }
                                                            
                
                

    /**
     * selects a collection of ContentSource objects pre-filled with their
     * Publisher objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContentSourcePeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinPublisher(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        ContentSourcePeer.addSelectColumns(c);
        int offset = numColumns + 1;
        PublisherPeer.addSelectColumns(c);


                        c.addJoin(ContentSourcePeer.PUBLISHER_ID,
            PublisherPeer.PUBLISHER_ID);
        

                                                                                                                                                        // check for conversion from boolean to Y/N
        if ( c.containsKey(IS_AUTHENTIFICATION_REQUIRED) )
        {
            Object possibleBoolean = c.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
                  
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record) rows.get(i);

                            Class omClass = ContentSourcePeer.getOMClass();
                    ContentSource obj1 = (ContentSource) ContentSourcePeer
                .row2Object(row, 1, omClass);
                     omClass = PublisherPeer.getOMClass();
                    Publisher obj2 = (Publisher)PublisherPeer
                .row2Object(row, offset, omClass);

            boolean newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                Publisher temp_obj2 = (Publisher)temp_obj1.getPublisher();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initContentSources();
                obj2.addContentSource(obj1);
            }
            results.add(obj1);
        }
        return results;
    }
                    
  
                                    
          
        
                                  
                

    /**
     * selects a collection of ContentSource objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContentSourcePeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinAllExceptContentSourceType(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to another value
        // so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                                    
                                                  
                    TransportPeer.addSelectColumns(c);
        int offset3 = offset2 + TransportPeer.numColumns;
                                                                
                    PublisherPeer.addSelectColumns(c);
        int offset4 = offset3 + PublisherPeer.numColumns;
                                                                                                                                                                                                    // check for conversion from boolean to Y/N
        if ( c.containsKey(IS_AUTHENTIFICATION_REQUIRED) )
        {
            Object possibleBoolean = c.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
                  
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record)rows.get(i);

                            Class omClass = ContentSourcePeer.getOMClass();
                    ContentSource obj1 = (ContentSource)ContentSourcePeer
                .row2Object(row, 1, omClass);
                                                
                                                                  
                                                        
                            
              
                           omClass = TransportPeer.getOMClass();
                          Transport obj2 = (Transport)TransportPeer
                .row2Object( row, offset2, omClass);

               boolean  newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                Transport temp_obj2 = (Transport)temp_obj1.getTransport();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initContentSources();
                obj2.addContentSource(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = PublisherPeer.getOMClass();
                          Publisher obj3 = (Publisher)PublisherPeer
                .row2Object( row, offset3, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                Publisher temp_obj3 = (Publisher)temp_obj1.getPublisher();
                if (temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj3.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initContentSources();
                obj3.addContentSource(obj1);
            }
                                                results.add(obj1);
        }
        return results;
    }
        
        
                                  
                

    /**
     * selects a collection of ContentSource objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContentSourcePeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinAllExceptTransport(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to another value
        // so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                                    
                    ContentSourceTypePeer.addSelectColumns(c);
        int offset3 = offset2 + ContentSourceTypePeer.numColumns;
                                                                
                                                  
                    PublisherPeer.addSelectColumns(c);
        int offset4 = offset3 + PublisherPeer.numColumns;
                                                                                                                                                                                                    // check for conversion from boolean to Y/N
        if ( c.containsKey(IS_AUTHENTIFICATION_REQUIRED) )
        {
            Object possibleBoolean = c.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
                  
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record)rows.get(i);

                            Class omClass = ContentSourcePeer.getOMClass();
                    ContentSource obj1 = (ContentSource)ContentSourcePeer
                .row2Object(row, 1, omClass);
                                                
                                                        
                            
              
                           omClass = ContentSourceTypePeer.getOMClass();
                          ContentSourceType obj2 = (ContentSourceType)ContentSourceTypePeer
                .row2Object( row, offset2, omClass);

               boolean  newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                ContentSourceType temp_obj2 = (ContentSourceType)temp_obj1.getContentSourceType();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initContentSources();
                obj2.addContentSource(obj1);
            }
                                                                    
                                                                  
                                                        
                            
              
                           omClass = PublisherPeer.getOMClass();
                          Publisher obj3 = (Publisher)PublisherPeer
                .row2Object( row, offset3, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                Publisher temp_obj3 = (Publisher)temp_obj1.getPublisher();
                if (temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj3.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initContentSources();
                obj3.addContentSource(obj1);
            }
                                                results.add(obj1);
        }
        return results;
    }
        
        
                                  
                

    /**
     * selects a collection of ContentSource objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in ContentSourcePeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinAllExceptPublisher(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to another value
        // so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                                    
                    ContentSourceTypePeer.addSelectColumns(c);
        int offset3 = offset2 + ContentSourceTypePeer.numColumns;
                                                                
                    TransportPeer.addSelectColumns(c);
        int offset4 = offset3 + TransportPeer.numColumns;
                                                                
                                                                                                                                                                                      // check for conversion from boolean to Y/N
        if ( c.containsKey(IS_AUTHENTIFICATION_REQUIRED) )
        {
            Object possibleBoolean = c.get(IS_AUTHENTIFICATION_REQUIRED);
            if (possibleBoolean instanceof Boolean)
            {
                if (((Boolean) possibleBoolean).booleanValue())
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "Y");
                }
                else
                {
                    c.add(IS_AUTHENTIFICATION_REQUIRED, "N");
                }
            }
         }
                  
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record)rows.get(i);

                            Class omClass = ContentSourcePeer.getOMClass();
                    ContentSource obj1 = (ContentSource)ContentSourcePeer
                .row2Object(row, 1, omClass);
                                                
                                                        
                            
              
                           omClass = ContentSourceTypePeer.getOMClass();
                          ContentSourceType obj2 = (ContentSourceType)ContentSourceTypePeer
                .row2Object( row, offset2, omClass);

               boolean  newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                ContentSourceType temp_obj2 = (ContentSourceType)temp_obj1.getContentSourceType();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initContentSources();
                obj2.addContentSource(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = TransportPeer.getOMClass();
                          Transport obj3 = (Transport)TransportPeer
                .row2Object( row, offset3, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                ContentSource temp_obj1 = (ContentSource)results.get(j);
                Transport temp_obj3 = (Transport)temp_obj1.getTransport();
                if (temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj3.addContentSource(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initContentSources();
                obj3.addContentSource(obj1);
            }
                                                                    
                                              results.add(obj1);
        }
        return results;
    }
                    
  
      /**
     * Returns the TableMap related to this peer.  This method is not
     * needed for general use but a specific application could have a need.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static TableMap getTableMap()
        throws TorqueException
    {
        return Torque.getDatabaseMap(DATABASE_NAME).getTable(TABLE_NAME);
    }
   }
