package net.sf.iquiver.om;

import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jul 12 19:24:20 CEST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ContentPeer
    extends net.sf.iquiver.om.cache.CacheBackedContentPeer
{
	final private static Log logger = LogFactory.getLog(ContentPeer.class);

	/**
	 * Retrieves a content document by it's uid
	 * @param uid
	 * @return
	 * @throws TorqueException
	 */
	public static Content retrieveByUID(String uid) throws TorqueException
	{
	    Content content = null;
	    Criteria crit = new Criteria();
	    crit.add( ContentPeer.CONTENT_UID, uid );
	    crit.add( ContentPeer.CONTENT_TO_DELETE, false );

	    List contents = ContentPeer.doSelect( crit );
	    
	    if( contents != null && !contents.isEmpty() )
	    {
	        content = (Content)contents.get(0);
	    }
	    
	    return content;
	}
}