
package net.sf.iquiver.om;


import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Mar 04 20:15:14 CET 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class ContentSource
    extends net.sf.iquiver.om.BaseContentSource
    implements Persistent
{
      
    
    public List getTransportConfigurationsForAuthentification(boolean mandatory_only) throws TorqueException
    {
        Criteria crit = new Criteria();
        crit.add(TransportAttributePeer.IS_PART_OF_AUTHENTIFICATION, true);
        
        if(mandatory_only)
        {
            crit.add(TransportAttributePeer.IS_MANDATORY, true);
        }
        
        return getContentSourceTransportConfigs(crit);
    }
    
    
}
