package net.sf.iquiver.om;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jul 12 19:24:20 CEST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class IqUserSearchQueryContentSourceLnkPeer
    extends net.sf.iquiver.om.cache.CacheBackedIqUserSearchQueryContentSourceLnkPeer
{
	final private static Log logger = LogFactory.getLog(IqUserSearchQueryContentSourceLnkPeer.class);
		
}