package net.sf.iquiver.om;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Mar 09 23:08:50 CET 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class PublisherPeer
    extends net.sf.iquiver.om.cache.CacheBackedPublisherPeer
{
	final private static Log logger = LogFactory.getLog(PublisherPeer.class);
		
}