/*********************************************************************
 * UserGroup.java
 * created on 12.06.2004 by netseeker
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/infoquiver/Repository/InfoQuiver/src/java/net/sf/iquiver/om/UserGroup.java,v $
 * $Date: 2004/07/17 17:14:42 $
 * $Revision: 1.6 $
 *********************************************************************/

package net.sf.iquiver.om;

import java.util.List;

import net.sf.iquiver.report.IReportSource;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jul 12 19:24:20 CEST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class UserGroup extends net.sf.iquiver.om.BaseUserGroup implements Persistent, IReportSource
{
    /** Fetches all ContentSources related to this UserGroup via UserGroupContentSourceLnk
     * @return a list of net.sf.iquiver.om.ContentSource objects
     * @throws TorqueException
     */
    public List getContentSources() throws TorqueException
    {
        Criteria crit = new Criteria();
        crit.addJoin( ContentSourcePeer.CONTENT_SOURCE_ID, UserGroupContentSourceLnkPeer.CONTENT_SOURCE_ID );
        crit.add( UserGroupContentSourceLnkPeer.USER_GROUP_ID, this.getUserGroupId() );

        return ContentSourcePeer.doSelect( crit );
    }
}