package net.sf.iquiver.om;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Jul 13 12:18:47 CEST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UserGroupContentSourceLnkPeer
    extends net.sf.iquiver.om.cache.CacheBackedUserGroupContentSourceLnkPeer
{
	final private static Log logger = LogFactory.getLog(UserGroupContentSourceLnkPeer.class);
		
}