
package net.sf.iquiver.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Jul 13 12:18:47 CEST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class UserGroupContentSourceLnk
    extends net.sf.iquiver.om.BaseUserGroupContentSourceLnk
    implements Persistent
{
}
