
INSERT INTO iq_user (USER_ID,USER_PASSWORD,USER_LOGIN,USER_FIRST_NAME,USER_LAST_NAME,USER_DATE_OF_BIRTH,ADDRESS_ID,CLIENT_ID)
    VALUES (0,'root','root','IQuivers','Root','2004-03-11 21:50:31.0',0,0);

INSERT INTO iq_user (USER_ID,USER_PASSWORD,USER_LOGIN,USER_FIRST_NAME,USER_LAST_NAME,USER_DATE_OF_BIRTH,ADDRESS_ID,CLIENT_ID)
    VALUES (1,'test','test','IQuivers','Testuser','2004-03-11 21:50:31.0',1,1);

INSERT INTO iq_client (CLIENT_ID,CLIENT_NAME,ADDRESS_ID)
    VALUES (0,'ROOT',0);

INSERT INTO iq_client (CLIENT_ID,CLIENT_NAME,ADDRESS_ID)
    VALUES (1,'TEST',1);

INSERT INTO iq_address (ADDRESS_ID,ADDRESS_NAME,ADDRESS_STREET,ADDRESS_ZIP,ADDRESS_EMAIL)
    VALUES (0,'DUMMY ADDRESS FOR ROOT','None','00000','netseeker@manskes.de');

INSERT INTO iq_address (ADDRESS_ID,ADDRESS_NAME,ADDRESS_STREET,ADDRESS_ZIP,ADDRESS_PHONE,ADDRESS_EMAIL,ADDRESS_NUMBER,ADDRESS_COUNTRY)
    VALUES (1,'TEST','Demo Square','00001','+(49)711 123456','netseeker@manskes.de','41','DE');

INSERT INTO iq_user_group (USER_GROUP_ID,USER_GROUP_NAME,USER_GROUP_DESC,CLIENT_ID)
    VALUES (0,'ROOT','ROOT',0);

INSERT INTO iq_user_group (USER_GROUP_ID,USER_GROUP_NAME,USER_GROUP_DESC,CLIENT_ID)
    VALUES (1,'TEST','TEST',1);

INSERT INTO iq_user_group_lnk (USER_GROUP_ID,USER_ID)
    VALUES (0,0);

INSERT INTO iq_user_group_lnk (USER_GROUP_ID,USER_ID)
    VALUES (1,1);

INSERT INTO iq_user_group_client_lnk (CLIENT_ID,USER_GROUP_ID)
    VALUES (0,0);

INSERT INTO iq_user_group_client_lnk (CLIENT_ID,USER_GROUP_ID)
    VALUES (1,1);

INSERT INTO iq_transport (TRANSPORT_ID,TRANSPORT_NAME,TRANSPORT_TYPE,TRANSPORT_DESC,TRANSPORT_START_TIMEOUT,TRANSPORT_IMPLEMENTATION)
    VALUES (0,'HTTPTransport',0,'Simple HTTP Transport','2004-03-16 00:07:15.0','net.sf.iquiver.transport.impl.HTTPTransport');

INSERT INTO iq_transport_attribute (TRANSPORT_ATTRIBUTE_ID,TRANSPORT_ID,TRANSPORT_ATTRIBUTE_NAME,TRANSPORT_ATTRIBUTE_TYPE,IS_PART_OF_AUTHENTIFICATION,IS_MANDATORY)
    VALUES (0,0,'Server','','N','Y');

INSERT INTO iq_transport_attribute (TRANSPORT_ATTRIBUTE_ID,TRANSPORT_ID,TRANSPORT_ATTRIBUTE_NAME,TRANSPORT_ATTRIBUTE_TYPE,IS_PART_OF_AUTHENTIFICATION,IS_MANDATORY)
    VALUES (1,0,'Port','','N','N');

INSERT INTO iq_transport_attribute (TRANSPORT_ATTRIBUTE_ID,TRANSPORT_ID,TRANSPORT_ATTRIBUTE_NAME,TRANSPORT_ATTRIBUTE_TYPE,IS_PART_OF_AUTHENTIFICATION,IS_MANDATORY)
    VALUES (2,0,'Login','','Y','N');

INSERT INTO iq_transport_attribute (TRANSPORT_ATTRIBUTE_ID,TRANSPORT_ID,TRANSPORT_ATTRIBUTE_NAME,TRANSPORT_ATTRIBUTE_TYPE,IS_PART_OF_AUTHENTIFICATION,IS_MANDATORY)
    VALUES (3,0,'Password','','Y','N');

INSERT INTO iq_permission (PERMISSION_ID,PERMISSION_NAME)
    VALUES (0,'');

INSERT INTO iq_content_source (CONTENT_SOURCE_ID,CONTENT_SOURCE_TYPE_ID,TRANSPORT_ID,CONTENT_SOURCE_NAME,CONTENT_SOURCE_DESC,IS_AUTHENTIFICATION_REQUIRED)
    VALUES (0,0,0,'HTML Test Content Source','HTML Test Content Source',N);

INSERT INTO iq_content_source_transport_config (CONTENT_SOURCE_ID,TRANSPORT_ATTRIBUTE_ID,TRANSPORT_ATTRIBUTE_VALUE)
    VALUES (0,0,'http://www.manskes.de');

INSERT INTO iq_content_parser (CONTENT_PARSER_ID,CONTENT_PARSER_IMPLEMENTATION,CONTENT_PARSER_NAME)
    VALUES (0,'net.sf.iquiver.parser.impl.TextParser','Text Parser');

INSERT INTO iq_content_parser (CONTENT_PARSER_ID,CONTENT_PARSER_IMPLEMENTATION,CONTENT_PARSER_NAME)
    VALUES (1,'net.sf.iquiver.parser.impl.HtmlParser','HTML Parser');

INSERT INTO iq_content_type (CONTENT_TYPE_ID,CONTENT_TYPE_NAME,CONTENT_TYPE_DESC,CONTENT_PARSER_ID)
    VALUES (0,'text/plain','Plain Text',0);

INSERT INTO iq_content_type (CONTENT_TYPE_ID,CONTENT_TYPE_NAME,CONTENT_TYPE_DESC,CONTENT_PARSER_ID)
    VALUES (1,'text/html','HTML',1);

